
name: release test

env:
  TZ: Asia/Shanghai

on:
  # 当master分支提交时
  workflow_dispatch:
  push:
    branches: 
      - code
jobs:
  main:
    runs-on: macos-latest
    steps:
# 开始任务
      - name: 安装UPX，拉取源码
        run: |
          mkdir /Users/Shared/xray/Xray-core
          cd /Users/Shared/xray
          mkdir /Users/Shared/xray/Xray-core
          cd /Users/Shared/xray/Xray-core
          wget https://github.com/xinb/Xray-core/releases/download/v1.2.4/Xray-windows-64-2021-02-01.zip
          
      - name: Update release
        uses: johnwbyrd/update-release@v1.0.0
        with:
          release: Xray-core-upx v1.2.4
          tag: v1.2.4
          message: 更改包名，保留未压缩版本，支持更多系统、架构
          body: https://github.com/XTLS/Xray-core/releases/tag/v1.2.4
          token: ${{ secrets.TOKEN }}
          files: /Users/Shared/xray/Xray-core
