name: xray推送测试

env:
  TZ: Asia/Shanghai

on:
  # 当master分支提交时
  workflow_dispatch:
  push:
    branches: 
      - code

# 开始任务
jobs:
  main:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    
    # 安装和构建
    - name: 安装UPX，拉取源码
      run: |
        mkdir /Users/Shared/xray
        cd /Users/Shared/xray
        git clone https://github.com/xinb/Xray-core.git
        cd /Users/Shared/xray/Xray-core
    - name: 编译linux
      run: |
       
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o xray -trimpath -ldflags "-s -w -buildid=" ./main
        zip -r Xray-Linux-64-$(date +'%Y-%m-%d %H:%M:%S').zip xray
        rm -f -r xray
    - name: Update dist folder to repository
      env:
        # 你的GitHub名字
        GITHUB_USERNAME: "xinb"
        # 你的邮箱
        EMAIL: ${{ secrets.EMAIL }}
        # GitHub Pages仓库名
        DIST_REPO: ${{ secrets.REP }}
        # GitHub Token
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        
      run: |
        mkdir /Users/Shared/xray/upload
        mv /Users/Shared/xray/Xray-core/Xray*  /Users/Shared/xray/upload
        git config --global user.email $GITHUB_USERNAME
        git config --global user.name $EMAIL
        
        cd /Users/Shared/xray/upload && git init && git add .
